/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantRegisterRouteImport } from './routes/merchant.register'
import { Route as MerchantLoginRouteImport } from './routes/merchant.login'
import { Route as MerchantDashboardRouteImport } from './routes/merchant.dashboard'
import { Route as MerchantDashboardIndexRouteImport } from './routes/merchant.dashboard.index'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRegisterRoute = MerchantRegisterRouteImport.update({
  id: '/merchant/register',
  path: '/merchant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant/login',
  path: '/merchant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/merchant/dashboard',
  path: '/merchant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDashboardIndexRoute = MerchantDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stores': typeof StoresRoute
  '/merchant/dashboard': typeof MerchantDashboardRouteWithChildren
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/merchant/dashboard/': typeof MerchantDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stores': typeof StoresRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/merchant/dashboard': typeof MerchantDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stores': typeof StoresRoute
  '/merchant/dashboard': typeof MerchantDashboardRouteWithChildren
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/merchant/dashboard/': typeof MerchantDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stores'
    | '/merchant/dashboard'
    | '/merchant/login'
    | '/merchant/register'
    | '/merchant/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stores'
    | '/merchant/login'
    | '/merchant/register'
    | '/merchant/dashboard'
  id:
    | '__root__'
    | '/'
    | '/stores'
    | '/merchant/dashboard'
    | '/merchant/login'
    | '/merchant/register'
    | '/merchant/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoresRoute: typeof StoresRoute
  MerchantDashboardRoute: typeof MerchantDashboardRouteWithChildren
  MerchantLoginRoute: typeof MerchantLoginRoute
  MerchantRegisterRoute: typeof MerchantRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/register': {
      id: '/merchant/register'
      path: '/merchant/register'
      fullPath: '/merchant/register'
      preLoaderRoute: typeof MerchantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/login': {
      id: '/merchant/login'
      path: '/merchant/login'
      fullPath: '/merchant/login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/merchant/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/dashboard/': {
      id: '/merchant/dashboard/'
      path: '/'
      fullPath: '/merchant/dashboard/'
      preLoaderRoute: typeof MerchantDashboardIndexRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
  }
}

interface MerchantDashboardRouteChildren {
  MerchantDashboardIndexRoute: typeof MerchantDashboardIndexRoute
}

const MerchantDashboardRouteChildren: MerchantDashboardRouteChildren = {
  MerchantDashboardIndexRoute: MerchantDashboardIndexRoute,
}

const MerchantDashboardRouteWithChildren =
  MerchantDashboardRoute._addFileChildren(MerchantDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoresRoute: StoresRoute,
  MerchantDashboardRoute: MerchantDashboardRouteWithChildren,
  MerchantLoginRoute: MerchantLoginRoute,
  MerchantRegisterRoute: MerchantRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
