/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreMerchantSlugRouteImport } from './routes/store.$merchantSlug'
import { Route as MerchantRegisterRouteImport } from './routes/merchant.register'
import { Route as MerchantLoginRouteImport } from './routes/merchant.login'
import { Route as MerchantDashboardRouteImport } from './routes/merchant.dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as MerchantDashboardIndexRouteImport } from './routes/merchant.dashboard.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as StoreMerchantSlugCheckoutRouteImport } from './routes/store.$merchantSlug.checkout'
import { Route as StoreMerchantSlugCartRouteImport } from './routes/store.$merchantSlug.cart'
import { Route as MerchantDashboardUsersRouteImport } from './routes/merchant.dashboard.users'
import { Route as MerchantDashboardStaffRouteImport } from './routes/merchant.dashboard.staff'
import { Route as MerchantDashboardSettingsRouteImport } from './routes/merchant.dashboard.settings'
import { Route as MerchantDashboardProductsRouteImport } from './routes/merchant.dashboard.products'
import { Route as MerchantDashboardOrdersRouteImport } from './routes/merchant.dashboard.orders'
import { Route as MerchantDashboardDeliveryRouteImport } from './routes/merchant.dashboard.delivery'
import { Route as MerchantDashboardChatbotRouteImport } from './routes/merchant.dashboard.chatbot'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as StoreMerchantSlugProductProductSlugRouteImport } from './routes/store.$merchantSlug.product.$productSlug'
import { Route as StoreMerchantSlugOrderOrderIdRouteImport } from './routes/store.$merchantSlug.order.$orderId'
import { Route as ApiPublicQpayWebhookRouteImport } from './routes/api.public.qpay.webhook'
import { Route as ApiPublicDeliveryWebhookRouteImport } from './routes/api.public.delivery.webhook'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreMerchantSlugRoute = StoreMerchantSlugRouteImport.update({
  id: '/store/$merchantSlug',
  path: '/store/$merchantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRegisterRoute = MerchantRegisterRouteImport.update({
  id: '/merchant/register',
  path: '/merchant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant/login',
  path: '/merchant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/merchant/dashboard',
  path: '/merchant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const MerchantDashboardIndexRoute = MerchantDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantDashboardRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreMerchantSlugCheckoutRoute =
  StoreMerchantSlugCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => StoreMerchantSlugRoute,
  } as any)
const StoreMerchantSlugCartRoute = StoreMerchantSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreMerchantSlugRoute,
} as any)
const MerchantDashboardUsersRoute = MerchantDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MerchantDashboardRoute,
} as any)
const MerchantDashboardStaffRoute = MerchantDashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => MerchantDashboardRoute,
} as any)
const MerchantDashboardSettingsRoute =
  MerchantDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MerchantDashboardRoute,
  } as any)
const MerchantDashboardProductsRoute =
  MerchantDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => MerchantDashboardRoute,
  } as any)
const MerchantDashboardOrdersRoute = MerchantDashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantDashboardRoute,
} as any)
const MerchantDashboardDeliveryRoute =
  MerchantDashboardDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => MerchantDashboardRoute,
  } as any)
const MerchantDashboardChatbotRoute =
  MerchantDashboardChatbotRouteImport.update({
    id: '/chatbot',
    path: '/chatbot',
    getParentRoute: () => MerchantDashboardRoute,
  } as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const StoreMerchantSlugProductProductSlugRoute =
  StoreMerchantSlugProductProductSlugRouteImport.update({
    id: '/product/$productSlug',
    path: '/product/$productSlug',
    getParentRoute: () => StoreMerchantSlugRoute,
  } as any)
const StoreMerchantSlugOrderOrderIdRoute =
  StoreMerchantSlugOrderOrderIdRouteImport.update({
    id: '/order/$orderId',
    path: '/order/$orderId',
    getParentRoute: () => StoreMerchantSlugRoute,
  } as any)
const ApiPublicQpayWebhookRoute = ApiPublicQpayWebhookRouteImport.update({
  id: '/api/public/qpay/webhook',
  path: '/api/public/qpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeliveryWebhookRoute =
  ApiPublicDeliveryWebhookRouteImport.update({
    id: '/api/public/delivery/webhook',
    path: '/api/public/delivery/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stores': typeof StoresRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/merchant/dashboard': typeof MerchantDashboardRouteWithChildren
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/store/$merchantSlug': typeof StoreMerchantSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/merchant/dashboard/chatbot': typeof MerchantDashboardChatbotRoute
  '/merchant/dashboard/delivery': typeof MerchantDashboardDeliveryRoute
  '/merchant/dashboard/orders': typeof MerchantDashboardOrdersRoute
  '/merchant/dashboard/products': typeof MerchantDashboardProductsRoute
  '/merchant/dashboard/settings': typeof MerchantDashboardSettingsRoute
  '/merchant/dashboard/staff': typeof MerchantDashboardStaffRoute
  '/merchant/dashboard/users': typeof MerchantDashboardUsersRoute
  '/store/$merchantSlug/cart': typeof StoreMerchantSlugCartRoute
  '/store/$merchantSlug/checkout': typeof StoreMerchantSlugCheckoutRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/merchant/dashboard/': typeof MerchantDashboardIndexRoute
  '/api/public/delivery/webhook': typeof ApiPublicDeliveryWebhookRoute
  '/api/public/qpay/webhook': typeof ApiPublicQpayWebhookRoute
  '/store/$merchantSlug/order/$orderId': typeof StoreMerchantSlugOrderOrderIdRoute
  '/store/$merchantSlug/product/$productSlug': typeof StoreMerchantSlugProductProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stores': typeof StoresRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/store/$merchantSlug': typeof StoreMerchantSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/merchant/dashboard/chatbot': typeof MerchantDashboardChatbotRoute
  '/merchant/dashboard/delivery': typeof MerchantDashboardDeliveryRoute
  '/merchant/dashboard/orders': typeof MerchantDashboardOrdersRoute
  '/merchant/dashboard/products': typeof MerchantDashboardProductsRoute
  '/merchant/dashboard/settings': typeof MerchantDashboardSettingsRoute
  '/merchant/dashboard/staff': typeof MerchantDashboardStaffRoute
  '/merchant/dashboard/users': typeof MerchantDashboardUsersRoute
  '/store/$merchantSlug/cart': typeof StoreMerchantSlugCartRoute
  '/store/$merchantSlug/checkout': typeof StoreMerchantSlugCheckoutRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/merchant/dashboard': typeof MerchantDashboardIndexRoute
  '/api/public/delivery/webhook': typeof ApiPublicDeliveryWebhookRoute
  '/api/public/qpay/webhook': typeof ApiPublicQpayWebhookRoute
  '/store/$merchantSlug/order/$orderId': typeof StoreMerchantSlugOrderOrderIdRoute
  '/store/$merchantSlug/product/$productSlug': typeof StoreMerchantSlugProductProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stores': typeof StoresRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/merchant/dashboard': typeof MerchantDashboardRouteWithChildren
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/store/$merchantSlug': typeof StoreMerchantSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/merchant/dashboard/chatbot': typeof MerchantDashboardChatbotRoute
  '/merchant/dashboard/delivery': typeof MerchantDashboardDeliveryRoute
  '/merchant/dashboard/orders': typeof MerchantDashboardOrdersRoute
  '/merchant/dashboard/products': typeof MerchantDashboardProductsRoute
  '/merchant/dashboard/settings': typeof MerchantDashboardSettingsRoute
  '/merchant/dashboard/staff': typeof MerchantDashboardStaffRoute
  '/merchant/dashboard/users': typeof MerchantDashboardUsersRoute
  '/store/$merchantSlug/cart': typeof StoreMerchantSlugCartRoute
  '/store/$merchantSlug/checkout': typeof StoreMerchantSlugCheckoutRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/merchant/dashboard/': typeof MerchantDashboardIndexRoute
  '/api/public/delivery/webhook': typeof ApiPublicDeliveryWebhookRoute
  '/api/public/qpay/webhook': typeof ApiPublicQpayWebhookRoute
  '/store/$merchantSlug/order/$orderId': typeof StoreMerchantSlugOrderOrderIdRoute
  '/store/$merchantSlug/product/$productSlug': typeof StoreMerchantSlugProductProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/driver'
    | '/login'
    | '/register'
    | '/stores'
    | '/account/orders'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/delivery'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/merchant/dashboard'
    | '/merchant/login'
    | '/merchant/register'
    | '/store/$merchantSlug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/merchant/dashboard/chatbot'
    | '/merchant/dashboard/delivery'
    | '/merchant/dashboard/orders'
    | '/merchant/dashboard/products'
    | '/merchant/dashboard/settings'
    | '/merchant/dashboard/staff'
    | '/merchant/dashboard/users'
    | '/store/$merchantSlug/cart'
    | '/store/$merchantSlug/checkout'
    | '/admin/blog/'
    | '/merchant/dashboard/'
    | '/api/public/delivery/webhook'
    | '/api/public/qpay/webhook'
    | '/store/$merchantSlug/order/$orderId'
    | '/store/$merchantSlug/product/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/driver'
    | '/login'
    | '/register'
    | '/stores'
    | '/account/orders'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/delivery'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/merchant/login'
    | '/merchant/register'
    | '/store/$merchantSlug'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/merchant/dashboard/chatbot'
    | '/merchant/dashboard/delivery'
    | '/merchant/dashboard/orders'
    | '/merchant/dashboard/products'
    | '/merchant/dashboard/settings'
    | '/merchant/dashboard/staff'
    | '/merchant/dashboard/users'
    | '/store/$merchantSlug/cart'
    | '/store/$merchantSlug/checkout'
    | '/admin/blog'
    | '/merchant/dashboard'
    | '/api/public/delivery/webhook'
    | '/api/public/qpay/webhook'
    | '/store/$merchantSlug/order/$orderId'
    | '/store/$merchantSlug/product/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/driver'
    | '/login'
    | '/register'
    | '/stores'
    | '/account/orders'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/delivery'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/merchant/dashboard'
    | '/merchant/login'
    | '/merchant/register'
    | '/store/$merchantSlug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/merchant/dashboard/chatbot'
    | '/merchant/dashboard/delivery'
    | '/merchant/dashboard/orders'
    | '/merchant/dashboard/products'
    | '/merchant/dashboard/settings'
    | '/merchant/dashboard/staff'
    | '/merchant/dashboard/users'
    | '/store/$merchantSlug/cart'
    | '/store/$merchantSlug/checkout'
    | '/admin/blog/'
    | '/merchant/dashboard/'
    | '/api/public/delivery/webhook'
    | '/api/public/qpay/webhook'
    | '/store/$merchantSlug/order/$orderId'
    | '/store/$merchantSlug/product/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DriverRoute: typeof DriverRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StoresRoute: typeof StoresRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MerchantDashboardRoute: typeof MerchantDashboardRouteWithChildren
  MerchantLoginRoute: typeof MerchantLoginRoute
  MerchantRegisterRoute: typeof MerchantRegisterRoute
  StoreMerchantSlugRoute: typeof StoreMerchantSlugRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicDeliveryWebhookRoute: typeof ApiPublicDeliveryWebhookRoute
  ApiPublicQpayWebhookRoute: typeof ApiPublicQpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/$merchantSlug': {
      id: '/store/$merchantSlug'
      path: '/store/$merchantSlug'
      fullPath: '/store/$merchantSlug'
      preLoaderRoute: typeof StoreMerchantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/register': {
      id: '/merchant/register'
      path: '/merchant/register'
      fullPath: '/merchant/register'
      preLoaderRoute: typeof MerchantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/login': {
      id: '/merchant/login'
      path: '/merchant/login'
      fullPath: '/merchant/login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/merchant/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/merchant/dashboard/': {
      id: '/merchant/dashboard/'
      path: '/'
      fullPath: '/merchant/dashboard/'
      preLoaderRoute: typeof MerchantDashboardIndexRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/$merchantSlug/checkout': {
      id: '/store/$merchantSlug/checkout'
      path: '/checkout'
      fullPath: '/store/$merchantSlug/checkout'
      preLoaderRoute: typeof StoreMerchantSlugCheckoutRouteImport
      parentRoute: typeof StoreMerchantSlugRoute
    }
    '/store/$merchantSlug/cart': {
      id: '/store/$merchantSlug/cart'
      path: '/cart'
      fullPath: '/store/$merchantSlug/cart'
      preLoaderRoute: typeof StoreMerchantSlugCartRouteImport
      parentRoute: typeof StoreMerchantSlugRoute
    }
    '/merchant/dashboard/users': {
      id: '/merchant/dashboard/users'
      path: '/users'
      fullPath: '/merchant/dashboard/users'
      preLoaderRoute: typeof MerchantDashboardUsersRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/merchant/dashboard/staff': {
      id: '/merchant/dashboard/staff'
      path: '/staff'
      fullPath: '/merchant/dashboard/staff'
      preLoaderRoute: typeof MerchantDashboardStaffRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/merchant/dashboard/settings': {
      id: '/merchant/dashboard/settings'
      path: '/settings'
      fullPath: '/merchant/dashboard/settings'
      preLoaderRoute: typeof MerchantDashboardSettingsRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/merchant/dashboard/products': {
      id: '/merchant/dashboard/products'
      path: '/products'
      fullPath: '/merchant/dashboard/products'
      preLoaderRoute: typeof MerchantDashboardProductsRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/merchant/dashboard/orders': {
      id: '/merchant/dashboard/orders'
      path: '/orders'
      fullPath: '/merchant/dashboard/orders'
      preLoaderRoute: typeof MerchantDashboardOrdersRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/merchant/dashboard/delivery': {
      id: '/merchant/dashboard/delivery'
      path: '/delivery'
      fullPath: '/merchant/dashboard/delivery'
      preLoaderRoute: typeof MerchantDashboardDeliveryRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/merchant/dashboard/chatbot': {
      id: '/merchant/dashboard/chatbot'
      path: '/chatbot'
      fullPath: '/merchant/dashboard/chatbot'
      preLoaderRoute: typeof MerchantDashboardChatbotRouteImport
      parentRoute: typeof MerchantDashboardRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/$merchantSlug/product/$productSlug': {
      id: '/store/$merchantSlug/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/store/$merchantSlug/product/$productSlug'
      preLoaderRoute: typeof StoreMerchantSlugProductProductSlugRouteImport
      parentRoute: typeof StoreMerchantSlugRoute
    }
    '/store/$merchantSlug/order/$orderId': {
      id: '/store/$merchantSlug/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/store/$merchantSlug/order/$orderId'
      preLoaderRoute: typeof StoreMerchantSlugOrderOrderIdRouteImport
      parentRoute: typeof StoreMerchantSlugRoute
    }
    '/api/public/qpay/webhook': {
      id: '/api/public/qpay/webhook'
      path: '/api/public/qpay/webhook'
      fullPath: '/api/public/qpay/webhook'
      preLoaderRoute: typeof ApiPublicQpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delivery/webhook': {
      id: '/api/public/delivery/webhook'
      path: '/api/public/delivery/webhook'
      fullPath: '/api/public/delivery/webhook'
      preLoaderRoute: typeof ApiPublicDeliveryWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantDashboardRouteChildren {
  MerchantDashboardChatbotRoute: typeof MerchantDashboardChatbotRoute
  MerchantDashboardDeliveryRoute: typeof MerchantDashboardDeliveryRoute
  MerchantDashboardOrdersRoute: typeof MerchantDashboardOrdersRoute
  MerchantDashboardProductsRoute: typeof MerchantDashboardProductsRoute
  MerchantDashboardSettingsRoute: typeof MerchantDashboardSettingsRoute
  MerchantDashboardStaffRoute: typeof MerchantDashboardStaffRoute
  MerchantDashboardUsersRoute: typeof MerchantDashboardUsersRoute
  MerchantDashboardIndexRoute: typeof MerchantDashboardIndexRoute
}

const MerchantDashboardRouteChildren: MerchantDashboardRouteChildren = {
  MerchantDashboardChatbotRoute: MerchantDashboardChatbotRoute,
  MerchantDashboardDeliveryRoute: MerchantDashboardDeliveryRoute,
  MerchantDashboardOrdersRoute: MerchantDashboardOrdersRoute,
  MerchantDashboardProductsRoute: MerchantDashboardProductsRoute,
  MerchantDashboardSettingsRoute: MerchantDashboardSettingsRoute,
  MerchantDashboardStaffRoute: MerchantDashboardStaffRoute,
  MerchantDashboardUsersRoute: MerchantDashboardUsersRoute,
  MerchantDashboardIndexRoute: MerchantDashboardIndexRoute,
}

const MerchantDashboardRouteWithChildren =
  MerchantDashboardRoute._addFileChildren(MerchantDashboardRouteChildren)

interface StoreMerchantSlugRouteChildren {
  StoreMerchantSlugCartRoute: typeof StoreMerchantSlugCartRoute
  StoreMerchantSlugCheckoutRoute: typeof StoreMerchantSlugCheckoutRoute
  StoreMerchantSlugOrderOrderIdRoute: typeof StoreMerchantSlugOrderOrderIdRoute
  StoreMerchantSlugProductProductSlugRoute: typeof StoreMerchantSlugProductProductSlugRoute
}

const StoreMerchantSlugRouteChildren: StoreMerchantSlugRouteChildren = {
  StoreMerchantSlugCartRoute: StoreMerchantSlugCartRoute,
  StoreMerchantSlugCheckoutRoute: StoreMerchantSlugCheckoutRoute,
  StoreMerchantSlugOrderOrderIdRoute: StoreMerchantSlugOrderOrderIdRoute,
  StoreMerchantSlugProductProductSlugRoute:
    StoreMerchantSlugProductProductSlugRoute,
}

const StoreMerchantSlugRouteWithChildren =
  StoreMerchantSlugRoute._addFileChildren(StoreMerchantSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DriverRoute: DriverRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StoresRoute: StoresRoute,
  BlogSlugRoute: BlogSlugRoute,
  MerchantDashboardRoute: MerchantDashboardRouteWithChildren,
  MerchantLoginRoute: MerchantLoginRoute,
  MerchantRegisterRoute: MerchantRegisterRoute,
  StoreMerchantSlugRoute: StoreMerchantSlugRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicDeliveryWebhookRoute: ApiPublicDeliveryWebhookRoute,
  ApiPublicQpayWebhookRoute: ApiPublicQpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
